import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/roboto-mono";
import NavBar from "@/src/components/layout/NavBar";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "my web-site",
  description: "Generated by danieltinois",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem={true}
          value={{
            dark: "dark",
            light: "light",
          }}
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
